TypeMorceaux:
    type: entity
    table: Type_Morceaux
    id:
        codeType:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: Code_Type
            generator:
                strategy: IDENTITY
    fields:
        libell„©Type:
            type: string
            nullable: false
            length: 20
            fixed: false
            column: Libell√©_Type
        description:
            type: string
            nullable: true
            length: 0
            fixed: false
            column: Description
    lifecycleCallbacks: {  }
