Achat:
    type: entity
    table: Achat
    indexes:
        IDX_E768AB52A1866919:
            columns:
                - Code_Enregistrement
        IDX_E768AB52D7B589C1:
            columns:
                - Code_Abonn√©
    id:
        codeAchat:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: Code_Achat
            generator:
                strategy: IDENTITY
    manyToOne:
        codeEnregistrement:
            targetEntity: Enregistrement
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                Code_Enregistrement:
                    referencedColumnName: Code_Morceau
            orphanRemoval: false
        codeAbonn„©:
            targetEntity: Abonn„©
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                Code_Abonn√©:
                    referencedColumnName: Code_Abonn√©
            orphanRemoval: false
    lifecycleCallbacks: {  }
