Oeuvre:
    type: entity
    table: Oeuvre
    indexes:
        IDX_32522BC898F61075:
            columns:
                - Code_Type
    id:
        codeOeuvre:
            type: integer
            nullable: false
            unsigned: false
            id: true
            column: Code_Oeuvre
            generator:
                strategy: IDENTITY
    fields:
        titreOeuvre:
            type: string
            nullable: false
            length: 200
            fixed: false
            column: Titre_Oeuvre
        sousTitre:
            type: string
            nullable: true
            length: 200
            fixed: false
            column: Sous_Titre
        tonalit„©:
            type: string
            nullable: true
            length: 20
            fixed: false
            column: Tonalit√©
        ann„©e:
            type: integer
            nullable: true
            unsigned: false
            column: Ann√©e
        opus:
            type: string
            nullable: true
            length: 20
            fixed: false
            column: Opus
        num„©roOpus:
            type: integer
            nullable: true
            unsigned: false
            column: Num√©ro_Opus
    manyToOne:
        codeType:
            targetEntity: TypeMorceaux
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                Code_Type:
                    referencedColumnName: Code_Type
            orphanRemoval: false
    lifecycleCallbacks: {  }
